export const GET_TEACHER_HISTORY_STATS = "GET_TEACHER_HISTORY_STATS"
export const GET_TEACHER_HISTORY_STATS_SUCCESS = "GET_TEACHER_HISTORY_STATS_SUCCESS"
export const GET_TEACHER_HISTORY_STATS_FAILURE = "GET_TEACHER_HISTORY_STATS_FAILURE"

export const GET_STUDENT_HISTORY_STATS = "GET_STUDENT_HISTORY_STATS"
export const GET_STUDENT_HISTORY_STATS_SUCCESS = "GET_STUDENT_HISTORY_STATS_SUCCESS"
export const GET_STUDENT_HISTORY_STATS_FAILURE = "GET_STUDENT_HISTORY_STATS_FAILURE"

export const GET_TEACHER_PAYMENT_PLAN = "GET_TEACHER_PAYMENT_PLAN"
export const GET_TEACHER_PAYMENT_PLAN_SUCCESS = "GET_TEACHER_PAYMENT_PLAN_SUCCESS"
export const GET_TEACHER_PAYMENT_PLAN_FAILURE = "GET_TEACHER_PAYMENT_PLAN_FAILURE"

export const POST_TEACHER_PAYMENT_PLAN = "POST_TEACHER_PAYMENT_PLAN"
export const POST_TEACHER_PAYMENT_PLAN_SUCCESS = "POST_TEACHER_PAYMENT_PLAN_SUCCESS"
export const POST_TEACHER_PAYMENT_PLAN_FAILURE = "POST_TEACHER_PAYMENT_PLAN_FAILURE"


export const UPDATE_TEACHER_PAYMENT_PLAN = "UPDATE_TEACHER_PAYMENT_PLAN"
export const UPDATE_TEACHER_PAYMENT_PLAN_SUCCESS = "UPDATE_TEACHER_PAYMENT_PLAN_SUCCESS"
export const UPDATE_TEACHER_PAYMENT_PLAN_FAILURE = "UPDATE_TEACHER_PAYMENT_PLAN_FAILURE"