export const GET_TEACHER_HISTORY_STATS = "GET_TEACHER_HISTORY_STATS"
export const GET_TEACHER_HISTORY_STATS_SUCCESS = "GET_TEACHER_HISTORY_STATS_SUCCESS"
export const GET_TEACHER_HISTORY_STATS_FAILURE = "GET_TEACHER_HISTORY_STATS_FAILURE"

export const GET_STUDENT_HISTORY_STATS = "GET_STUDENT_HISTORY_STATS"
export const GET_STUDENT_HISTORY_STATS_SUCCESS = "GET_STUDENT_HISTORY_STATS_SUCCESS"
export const GET_STUDENT_HISTORY_STATS_FAILURE = "GET_STUDENT_HISTORY_STATS_FAILURE"