export const GET_ADMINS = "GET_ADMINS"
export const GET_ADMINS_SUCCESS = "GET_ADMINS_SUCCESS"
export const GET_ADMINS_FAILURE = "GET_ADMINS_FAILURE"

export const GET_ADMIN_DETAIL = "GET_ADMIN_DETAIL"
export const GET_ADMIN_DETAIL_SUCCESS = "GET_ADMIN_DETAIL_SUCCESS"
export const GET_ADMIN_DETAIL_FAILURE = "GET_ADMIN_DETAIL_FAILURE"

export const REGISTER_ADMIN = "REGISTER_ADMIN"
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS"
export const REGISTER_ADMIN_FAILURE = "REGISTER_ADMIN_FAILURE"