export const POST_ASSIGN_TEACHER = "POST_ASSIGN_TEACHER"
export const POST_ASSIGN_TEACHER_SUCCESS = "POST_ASSIGN_TEACHER_SUCCESS"
export const POST_ASSIGN_TEACHER_FAILURE = "POST_ASSIGN_TEACHER_FAILURE"

export const UNASSIGN_TEACHER = "UNASSIGN_TEACHER"
export const UNASSIGN_TEACHER_SUCCESS = "UNASSIGN_TEACHER_SUCCESS"
export const UNASSIGN_TEACHER_FAILURE = "UNASSIGN_TEACHER_FAILURE"