
export const POST_EBOOK = "POST_EBOOK"
export const POST_EBOOK_SUCCESS = "POST_EBOOK_SUCCESS"
export const POST_EBOOK_FAILURE = "POST_EBOOK_FAILURE"


export const GET_EBOOKS = "GET_EBOOKS"
export const GET_EBOOKS_SUCCESS = "GET_EBOOKS_SUCCESS"
export const GET_EBOOKS_FAILURE = "GET_EBOOKS_FAILURE"


export const PUT_EBOOK = "PUT_EBOOK"
export const PUT_EBOOK_SUCCESS = "PUT_EBOOK_SUCCESS"
export const PUT_EBOOK_FAILURE = "PUT_EBOOK_FAILURE"