export const UPDATE_ADMIN_PROFILE = "UPDATE_ADMIN_PROFILE"
export const UPDATE_ADMIN_PROFILE_SUCCESS = "UPDATE_ADMIN_PROFILE_SUCCESS"
export const UPDATE_ADMIN_PROFILE_FAILURE = "UPDATE_ADMIN_PROFILE_FAILURE"

export const UPDATE_TEACHER_PROFILE = "UPDATE_TEACHER_PROFILE"
export const UPDATE_TEACHER_PROFILE_SUCCESS = "UPDATE_TEACHER_PROFILE_SUCCESS"
export const UPDATE_TEACHER_PROFILE_FAILURE = "UPDATE_TEACHER_PROFILE_FAILURE"

export const UPDATE_STUDENT_PROFILE = "UPDATE_STUDENT_PROFILE"
export const UPDATE_STUDENT_PROFILE_SUCCESS = "UPDATE_STUDENT_PROFILE_SUCCESS"
export const UPDATE_STUDENT_PROFILE_FAILURE = "UPDATE_STUDENT_PROFILE_FAILURE"


export const UPDATE_ADMIN_PROFILE_PICTURE = "UPDATE_ADMIN_PROFILE_PICTURE"
export const UPDATE_ADMIN_PROFILE_PICTURE_SUCCESS = "UPDATE_ADMIN_PROFILE_PICTURE_SUCCESS"
export const UPDATE_ADMIN_PROFILE_PICTURE_FAILURE = "UPDATE_ADMIN_PROFILE_PICTURE_FAILURE"

export const UPDATE_TEACHER_PROFILE_PICTURE = "UPDATE_TEACHER_PROFILE_PICTURE"
export const UPDATE_TEACHER_PROFILE_PICTURE_SUCCESS = "UPDATE_TEACHER_PROFILE_PICTURE_SUCCESS"
export const UPDATE_TEACHER_PROFILE_PICTURE_FAILURE = "UPDATE_TEACHER_PROFILE_PICTURE_FAILURE"

export const UPDATE_STUDENT_PROFILE_PICTURE = "UPDATE_STUDENT_PROFILE_PICTURE"
export const UPDATE_STUDENT_PROFILE_PICTURE_SUCCESS = "UPDATE_STUDENT_PROFILE_PICTURE_SUCCESS"
export const UPDATE_STUDENT_PROFILE_PICTURE_FAILURE = "UPDATE_STUDENT_PROFILE_PICTURE_FAILURE"


export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS"
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE"