export const GET_STUDENTS_STATS = "GET_STUDENTS_STATS"
export const GET_STUDENTS_STATS_SUCCESS = "GET_STUDENTS_STATS_SUCCESS"
export const GET_STUDENTS_STATS_FAILURE = "GET_STUDENTS_STATS_FAILURE"

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS"
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS"
export const GET_ALL_STUDENTS_FAILURE = "GET_ALL_STUDENTS_FAILURE"

export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS"
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS"
export const GET_STUDENT_DETAILS_FAILURE = "GET_STUDENT_DETAILS_FAILURE"

export const GET_STUDENT_NEW_OR_WAITING_STATUS = "GET_STUDENT_NEW_OR_WAITING_STATUS"
export const GET_STUDENT_NEW_OR_WAITING_STATUS_SUCCESS = "GET_STUDENT_NEW_OR_WAITING_STATUS_SUCCESS"
export const GET_STUDENT_NEW_OR_WAITING_STATUS_FAILURE = "GET_STUDENT_NEW_OR_WAITING_STATUS_FAILURE"

export const GET_ACTIVE_STUDENTS = "GET_ACTIVE_STUDENTS"
export const GET_ACTIVE_STUDENTS_SUCCESS = "GET_ACTIVE_STUDENTS_SUCCESS"
export const GET_ACTIVE_STUDENTS_FAILURE = "GET_ACTIVE_STUDENTS_FAILURE"

export const ON_SEARCH_CHANGE = "ON_SEARCH_CHANGE"


