export const GET_STUDENTS_STATS = "GET_STUDENTS_STATS"
export const GET_STUDENTS_STATS_SUCCESS = "GET_STUDENTS_STATS_SUCCESS"
export const GET_STUDENTS_STATS_FAILURE = "GET_STUDENTS_STATS_FAILURE"

export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS"
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS"
export const GET_STUDENT_DETAILS_FAILURE = "GET_STUDENT_DETAILS_FAILURE"


