export const GET_TEACHERS_STATS = "GET_TEACHERS_STATS"
export const GET_TEACHERS_STATS_SUCCESS = "GET_TEACHERS_STATS_SUCCESS"
export const GET_TEACHERS_STATS_FAILURE = "GET_TEACHERS_STATS_FAILURE"

export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS"
export const GET_ALL_TEACHERS_SUCCESS = "GET_ALL_TEACHERS_SUCCESS"
export const GET_ALL_TEACHERS_FAILURE = "GET_ALL_TEACHERS_FAILURE"

export const GET_TEACHER_DETAILS = "GET_TEACHER_DETAILS"
export const GET_TEACHER_DETAILS_SUCCESS = "GET_TEACHER_DETAILS_SUCCESS"
export const GET_TEACHER_DETAILS_FAILURE = "GET_TEACHER_DETAILS_FAILURE"

export const GET_TEACHER_STUDENTS = "GET_TEACHER_STUDENTS"
export const GET_TEACHER_STUDENTS_SUCCESS = "GET_TEACHER_STUDENTS_SUCCESS"
export const GET_TEACHER_STUDENTS_FAILURE = "GET_TEACHER_STUDENTS_FAILURE"

export const ON_SEARCH_TEACHER_CHANGE = "ON_SEARCH_TEACHER_CHANGE"