export const GET_TEACHERS = "GET_TEACHERS"
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS"
export const GET_TEACHERS_FAILURE = "GET_TEACHERS_FAILURE"

export const GET_TEACHER_DETAILS = "GET_TEACHER_DETAILS"
export const GET_TEACHER_DETAILS_SUCCESS = "GET_TEACHER_DETAILS_SUCCESS"
export const GET_TEACHER_DETAILS_FAILURE = "GET_TEACHER_DETAILS_FAILURE"


