export const GET_TEACHERS_STATS = "GET_TEACHERS_STATS"
export const GET_TEACHERS_STATS_SUCCESS = "GET_TEACHERS_STATS_SUCCESS"
export const GET_TEACHERS_STATS_FAILURE = "GET_TEACHERS_STATS_FAILURE"

export const GET_TEACHER_DETAILS = "GET_TEACHER_DETAILS"
export const GET_TEACHER_DETAILS_SUCCESS = "GET_TEACHER_DETAILS_SUCCESS"
export const GET_TEACHER_DETAILS_FAILURE = "GET_TEACHER_DETAILS_FAILURE"


